CREATE TABLE team
(
    team_id         bigint                      NOT NULL generated by default as identity,
    name            varchar(32)                NOT NULL,
    primary key (team_id)
);

..
..
